language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

services:
  - mysql

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - mysql < ./tests/database/testing.sql -u root
  - ./libs/bin/tester -s ./tests/

allow_failures:
  - php: nightly

after_failure:
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
